/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF) Configuration Header
 */
#pragma once

/* ESP32 Chip Configuration */
#define CONFIG_IDF_TARGET_ESP32 1
#define CONFIG_IDF_TARGET "esp32"
#define CONFIG_IDF_FIRMWARE_CHIP_ID 0x0000

/* Arduino Configuration */
#define CONFIG_ARDUINO_RUNNING_CORE 1
#define CONFIG_ARDUINO_EVENT_RUNNING_CORE 1

/* FreeRTOS Configuration */
#define CONFIG_FREERTOS_UNICORE 0
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION 1
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_PTRVAL 1
#define CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK 1

/* ESP32-specific Configuration */
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_240 1
#define CONFIG_ESP32_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_TYPE_AUTO 1

/* Memory Configuration */
#define CONFIG_SPIRAM_BOOT_INIT 1
#define CONFIG_SPIRAM_IGNORE_NOTFOUND 1
#define CONFIG_SPIRAM_USE 1
#define CONFIG_SPIRAM_OCCUPY_VSPI_HOST 1
#define CONFIG_SPIRAM_USE_MEMMAP 1

/* WiFi Configuration */
#define CONFIG_ESP32_WIFI_ENABLED 1
#define CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE 1
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 10
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM 32

/* TCP Configuration */
#define CONFIG_LWIP_TCP_OVERSIZE_MSS 1

/* Bluetooth Configuration */
#define CONFIG_BT_ENABLED 1
#define CONFIG_BTDM_CTRL_MODE_BLE_ONLY 1
#define CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY 1
#define CONFIG_BTDM_CTRL_MODE_BTDM 1

/* Log Configuration */
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_MAXIMUM_EQUALS_DEFAULT 1
#define CONFIG_LOG_MAXIMUM_LEVEL 3

/* Component Configuration */
#define CONFIG_LWIP_PPP_SUPPORT 1
#define CONFIG_LWIP_IPV6 1

/* Security features */
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH 1
#define CONFIG_ESP32_ENABLE_COREDUMP 1

/* Flash Configuration */
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1

/* Partition Configuration */
#define CONFIG_PARTITION_TABLE_CUSTOM 1
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"

/* Arduino specific defines */
#define CONFIG_ARDUHAL_ESP_LOG 1
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL 3

/* USB Configuration */
#define CONFIG_ESP_CONSOLE_USB_CDC 1

/* Camera Configuration */
#define CONFIG_CAMERA_CORE0 1
#define CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX 32768

/* Audio Configuration */
#define CONFIG_ESP32_AUDIO_SUPPORTED 1

/* TensorFlow Lite Configuration */
#define CONFIG_TFLITE_MICRO_SUPPORTED 1

/* Network Configuration */
#define CONFIG_LWIP_LOCAL_HOSTNAME "esp32cam"