/*
 * TensorFlow Lite Model Data Header
 * ==================================
 * 
 * This file declares the TFLite model data array.
 * DO NOT EDIT MANUALLY - Generated by convert_model_to_header.py
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <Arduino.h>

#ifdef __cplusplus
extern "C" {
#endif

// Model data array - stored in flash memory
extern const unsigned char noise_classifier_model_data[] PROGMEM;
extern const unsigned int noise_classifier_model_data_len;

#ifdef __cplusplus
}
#endif

#endif // MODEL_DATA_H
