
#!/usr/bin/env python3
"""
Convert TFLite Model to C Header File for Arduino/ESP32
========================================================

This script converts the quantized TFLite model to a C header file
that can be included in Arduino/ESP32 projects.

Usage:
    python convert_model_to_header.py

Generates:
    arduino_esp32/noise_classifier_esp32/model_data.cpp
    arduino_esp32/noise_classifier_esp32/model_data.h
"""

import os
import sys
from pathlib import Path

def convert_tflite_to_header(tflite_path, output_cpp_path, output_h_path):
    """
    Convert TFLite model file to C++ header and implementation files
    
    Args:
        tflite_path: Path to .tflite model file
        output_cpp_path: Path for output .cpp file
        output_h_path: Path for output .h file
    """
    
    print(f"Converting TFLite model to C array...")
    print(f"  Input: {tflite_path}")
    print(f"  Output CPP: {output_cpp_path}")
    print(f"  Output H: {output_h_path}")
    
    # Read the TFLite model
    if not os.path.exists(tflite_path):
        print(f"Error: Model file not found: {tflite_path}")
        return False
    
    with open(tflite_path, 'rb') as f:
        model_data = f.read()
    
    model_size = len(model_data)
    print(f"  Model size: {model_size} bytes ({model_size/1024:.1f} KB)")
    
    # Create output directory if needed
    os.makedirs(os.path.dirname(output_cpp_path), exist_ok=True)
    
    # Generate CPP file
    with open(output_cpp_path, 'w') as f:
        f.write("""/*
 * Auto-generated TensorFlow Lite Model Data
 * ==========================================
 * 
 * This file contains the quantized TFLite model as a C array.
 * DO NOT EDIT MANUALLY - Generated by convert_model_to_header.py
 * 
 * Model: Noise Classifier (4 classes)
 * Classes: Whispering, Typing, Phone_ringing, Loud_talking
 */

#include "model_data.h"

// Model data array
alignas(8) const unsigned char noise_classifier_model_data[] = {
""")
        
        # Write model bytes (16 bytes per line)
        for i in range(0, len(model_data), 16):
            line_bytes = model_data[i:i+16]
            hex_bytes = ', '.join([f'0x{b:02x}' for b in line_bytes])
            f.write(f"  {hex_bytes}")
            
            if i + 16 < len(model_data):
                f.write(",\n")
            else:
                f.write("\n")
        
        f.write("};\n\n")
        f.write(f"const unsigned int noise_classifier_model_data_len = {model_size};\n")
    
    # Generate header file
    with open(output_h_path, 'w') as f:
        f.write("""/*
 * TensorFlow Lite Model Data Header
 * ==================================
 * 
 * This file declares the TFLite model data array.
 * DO NOT EDIT MANUALLY - Generated by convert_model_to_header.py
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// Model data array
extern const unsigned char noise_classifier_model_data[];
extern const unsigned int noise_classifier_model_data_len;

#ifdef __cplusplus
}
#endif

#endif // MODEL_DATA_H
""")
    
    print(f"✅ Conversion complete!")
    print(f"   Generated {len(model_data)} bytes of model data")
    print(f"   Files created:")
    print(f"     - {output_cpp_path}")
    print(f"     - {output_h_path}")
    
    return True


def main():
    # Paths
    script_dir = Path(__file__).parent
    tflite_model_path = script_dir / 'models' / 'noise_classifier_quantized.tflite'
    output_cpp_path = script_dir / 'arduino_esp32' / 'noise_classifier_esp32' / 'model_data.cpp'
    output_h_path = script_dir / 'arduino_esp32' / 'noise_classifier_esp32' / 'model_data.h'
    
    print("=" * 60)
    print("TFLite to Arduino/ESP32 Header Converter")
    print("=" * 60)
    print()
    
    # Check if TFLite model exists
    if not tflite_model_path.exists():
        print(f"❌ Error: TFLite model not found!")
        print(f"   Expected location: {tflite_model_path}")
        print()
        print("Please run the conversion script first:")
        print("   python convert_to_tflite.py")
        return 1
    
    # Convert the model
    success = convert_tflite_to_header(
        str(tflite_model_path),
        str(output_cpp_path),
        str(output_h_path)
    )
    
    if success:
        print()
        print("=" * 60)
        print("🎉 SUCCESS! Model ready for Arduino/ESP32")
        print("=" * 60)
        print()
        print("Next steps:")
        print("1. Open arduino_esp32/noise_classifier_esp32/ in Arduino IDE")
        print("2. Install required libraries:")
        print("   - TensorFlowLite_ESP32 (by TensorFlow Authors)")
        print("3. Select board: ESP32 Dev Module")
        print("4. Upload to your ESP32 WROOM 32")
        print()
        return 0
    else:
        print()
        print("❌ Conversion failed!")
        return 1


if __name__ == "__main__":
    exit(main())
